package edu.bcm.dldcc.big.acquire.shipment;

/**
 * Enum representing Shipment form terms
 * TODO This should be II8n
 * @author amcowiti
 *
 */
public enum NaLabShipmentFormTerms {

	TITLE("Tissue Intake",null),
	VERSION("version 1.0.5.2",null),
	CUSTOM_DATA("Custom Data",null),
	DATE_RECIVED("Date Received",null),
	TIME_RECEIVED("Time Received",null),
	COLLABORATOR_EXT("External collaborator",null),
	COLLABORATOR_HGSC("Internal HGSC collaborator",null),
	INFO_TITLE("No information in this form should encode patient identifying information.",
			NaLabShipmentFormColor.RED),
	INFO_DESC("The present intake form is divided in 2 sections: the tissue and the blood, starting at row 17 and 123, respectively.  Please input the details of each sample being submitted in the appropriate section (one sample per row).  The input for each section is slightly different.  The form should be submitted before the samples are brought to the HGSC.  It will be reviewed and sent back for any correction if necessary.  No samples will be accepted without the approval of this form. (Generated by Acquire)",
			NaLabShipmentFormColor.RED),
	SECTION_TITLE_TISSUE("Tissue Section",NaLabShipmentFormColor.RED),
	SECTION_TITLE_BLOOD("Body Fluid Section",NaLabShipmentFormColor.RED);
	
	private String term;
	private NaLabShipmentFormColor color;

	public String getTerm() {
		return term;
	}
	

	public NaLabShipmentFormColor getColor() {
		return color;
	}


	private NaLabShipmentFormTerms(String term,NaLabShipmentFormColor color) {
		this.term = term;
		this.color=(color==null)?NaLabShipmentFormColor.DEFAULT:color;
	}


	@Override
	public String toString() {
		return term;
	}
	
	
}
